spring:
  config:
    activate:
      on-profile: external

# 기상청 api key
weather-station:
  short-term:
    apikey: ${WEATHER_STATION_SHORT_TERM_API_KEY}
  mid-term:
    apikey: ${WEATHER_STATION_MID_TERM_API_KEY}

kakao:
  local:
    apikey: ${KAKAO_LOCAL_API_KEY}

# 국가농작물병해충관리시스템(NCPMS) api key
ncpms:
  apikey: ${NCPMS_API_KEY}

# AI 챗봇 서버 URL
chatbot:
  api:
    url: ${AI_SERVER_URL}
